version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8082:80
    volumes:
      - joomla:/var/www/html      
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    volumes:
      - joomlamysql:/var/lib/mysql     
    environment:
      MYSQL_ROOT_PASSWORD: example
volumes:
  joomlamysql:
  joomla:        
      
